const { getDefaultConfig } = require('expo/metro-config');

const config = getDefaultConfig(__dirname);

// The raw-terminal mirror ships a self-contained xterm.js page as a bundled
// asset (src/terminal/xterm.html, generated by scripts/buildXtermHtml.mjs);
// html is not an asset extension by default.
config.resolver.assetExts = [...config.resolver.assetExts, 'html'];

module.exports = config;
