// getSentryExpoConfig wraps expo/metro-config's getDefaultConfig and adds the
// serializer that stamps a debug ID into the bundle. Without it, an uploaded
// source map cannot be matched to the bundle that produced a crash, so every
// release stack trace arrives minified - a silent failure, since the build and
// the upload both still succeed. Safe when Sentry is unconfigured: the debug ID
// is inert without a DSN. Do NOT revert this to getDefaultConfig.
const { getSentryExpoConfig } = require('@sentry/react-native/metro');

const config = getSentryExpoConfig(__dirname);

// The raw-terminal mirror ships a self-contained xterm.js page as a bundled
// asset (src/terminal/xterm.html, generated by scripts/buildXtermHtml.mjs);
// html is not an asset extension by default.
config.resolver.assetExts = [...config.resolver.assetExts, 'html'];

module.exports = config;
