// '@expo/config-plugins', not 'expo/config-plugins'. The latter subpath does not
// exist in SDK 57; see the comment in withAndroidPushService.ts for what that
// cost.
import { withPodfile, type ConfigPlugin } from '@expo/config-plugins';

/**
 * Guards `pod install` against CocoaPods' sequential-UUID collision bug, which
 * writes a Pods.xcodeproj that Xcode cannot open.
 *
 * THE BUG. CocoaPods' `Pod::Project` pre-generates object UUIDs with a fast
 * sequential counter that skips collision checks, and a mid-install counter
 * reset can hand a later object a UUID that is already taken. When the victim
 * is the root object, the objects table keeps only the newcomer, the saved
 * Pods.xcodeproj has no PBXProject at all, and every xcodebuild invocation
 * fails with "The project 'Pods' is damaged and cannot be opened" via an
 * `-[XCSwiftPackageProductDependency _setSavedArchiveVersion:] unrecognized
 * selector` crash: Xcode resolves `rootObject` to the Swift-package product
 * dependency that took the root's UUID.
 *
 * OBSERVED HERE. build-ios.yml run 31909442213 captured the corrupt file: the
 * RaTeX product dependency (added for react-native-enriched-markdown by
 * react-native's `spm.rb` inside `react_native_post_install`) held the root
 * object's UUID `46EB2E00000000`, and the PBXProject object was gone. The
 * trigger was the 2026-08-15 Expo SDK 57 patch realign shifting the pod
 * graph's object count so the reset landed exactly on zero; the bug itself is
 * upstream and input-shape dependent.
 *
 * WHY EXPO'S OWN GUARD DOES NOT COVER THIS. expo-modules-autolinking installs
 * the same collision-safe generator (scripts/ios/cocoapods/installer.rb), but
 * only inside `perform_post_install_actions`, which runs AFTER the Podfile's
 * `post_install` hook. The SPM objects `spm.rb` creates live in that earlier,
 * unprotected window. This plugin injects the guard at the TOP of the
 * `post_install` block, before `react_native_post_install` runs, and also
 * purges any already-queued UUID that collides with an existing object.
 *
 * CNG: this is how the generated Podfile gets native config
 * (.claude/rules/expo-cng.md). The generated file is never hand-edited and
 * never committed. Drop this plugin once Expo or CocoaPods fixes the
 * generator upstream.
 */

/**
 * Idempotency anchor. `expo prebuild` regenerates the Podfile from the
 * template on a clean run but can merge into an existing file otherwise, so
 * the block has to be able to recognise itself.
 */
export const PODS_UUID_COLLISION_GUARD_ANCHOR = '# kangentic:pods-uuid-collision-guard';

/**
 * The Ruby injected at the top of the `post_install` block. Mirrors the shape
 * of expo-modules-autolinking's own late-window guard so the gem-internal
 * surface it touches (`objects_by_uuid`, `@available_uuids`,
 * `@generated_uuids`, `define_singleton_method`) is one CocoaPods already
 * exercises in the same process.
 */
export const PODS_UUID_COLLISION_GUARD_BLOCK = `${PODS_UUID_COLLISION_GUARD_ANCHOR}
    # CocoaPods pre-generates object UUIDs with a fast sequential counter that
    # skips collision checks; a mid-install counter reset can hand a new object
    # an existing UUID. When the victim is the root object the saved
    # Pods.xcodeproj has no PBXProject and xcodebuild reports "The project
    # 'Pods' is damaged". expo-modules-autolinking installs this same
    # collision-safe generator too late for the SPM objects created inside this
    # hook, so guard the whole hook here. Generated by
    # plugins/withIosPodsUuidCollisionGuard.ts, which carries the full
    # reasoning. Do not hand-edit: ios/ is a prebuild artifact.
    pods_uuid_guard_project = installer.pods_project
    pods_uuid_guard_existing = pods_uuid_guard_project.objects_by_uuid.keys.to_set
    pods_uuid_guard_queued = pods_uuid_guard_project.instance_variable_get(:@available_uuids)
    pods_uuid_guard_queued.reject! { |queued_uuid| pods_uuid_guard_existing.include?(queued_uuid) } unless pods_uuid_guard_queued.nil?
    pods_uuid_guard_project.define_singleton_method(:generate_available_uuid_list) do |count = 100|
      random_uuids = (0..count).map { SecureRandom.hex(12).upcase }
      unique_uuids = random_uuids.reject { |random_uuid| pods_uuid_guard_existing.include?(random_uuid) || @generated_uuids.include?(random_uuid) }
      @generated_uuids += unique_uuids
      @available_uuids += unique_uuids
    end`;

/**
 * Inserts the guard as the first statement of the `post_install` block.
 *
 * Idempotent via the anchor. Throws rather than no-opping when the hook line
 * is missing: a template change upstream must fail prebuild loudly instead of
 * quietly turning the guard off and shipping the corruption back to CI (the
 * same posture as withAndroidCmakeBuildStaging's Groovy-language check).
 */
export function applyPodsUuidCollisionGuard(contents: string): string {
  if (contents.includes(PODS_UUID_COLLISION_GUARD_ANCHOR)) {
    return contents;
  }
  const postInstallHookPattern = /^([ \t]*)post_install do \|installer\|[ \t]*$/m;
  const hookMatch = contents.match(postInstallHookPattern);
  if (!hookMatch || hookMatch.index === undefined) {
    throw new Error(
      "withIosPodsUuidCollisionGuard could not find `post_install do |installer|` in the generated Podfile. " +
        'The upstream template changed; re-anchor the guard before building for iOS.'
    );
  }
  const insertAt = hookMatch.index + hookMatch[0].length;
  const hookIndent = hookMatch[1];
  const guard = `\n${hookIndent}  ${PODS_UUID_COLLISION_GUARD_BLOCK}`;
  return `${contents.slice(0, insertAt)}${guard}${contents.slice(insertAt)}`;
}

const withIosPodsUuidCollisionGuard: ConfigPlugin = (config) => {
  return withPodfile(config, (podfileConfig) => {
    podfileConfig.modResults.contents = applyPodsUuidCollisionGuard(podfileConfig.modResults.contents);
    return podfileConfig;
  });
};

export default withIosPodsUuidCollisionGuard;
