import { PROTOCOL_VERSION, x25519PublicKeyFrom, type PairingQrPayload, type X25519KeyPair } from '@kangentic/protocol';
import type { TrustAnchor } from '@/pairing/trustAnchor';

/**
 * The reviewer/demo pairing identity.
 *
 * WHY THIS EXISTS. Every real pairing code is a single-use, short-lived token
 * mixed into the Noise handshake as a pre-shared key, so a code printed in a
 * screenshot or a video is always dead by the time anyone opens it. App Review
 * turnaround is measured in days; a real code's intended lifetime is minutes.
 * iOS App Review rejected three consecutive builds on Guideline 2.1(a) for
 * exactly that reason, having genuinely tried a code from an attached recording
 * and been told it had expired. This module is the permanent, non-expiring
 * alternative: it pairs the phone against an in-process desktop peer, so there
 * is nothing to expire and no desktop or network to arrange.
 *
 * NONE OF THE KEY MATERIAL BELOW IS A SECRET, and it is derived from readable
 * ASCII labels rather than committed as raw key bytes so that stays obvious to
 * a reader and to a secret scanner. It authenticates a peer that runs on the
 * same device as the code checking it, so possessing it grants exactly what
 * running the app already grants: a view of fixture content. There is no
 * confidentiality to lose. A raw 32-byte literal here would be indistinguishable
 * from a leaked desktop key at a glance, which is the only real risk this
 * derivation removes.
 */

/**
 * `encodePairingQrPayload` requires exactly this many bytes and throws
 * otherwise (see the package's `pairing/qr.ts`). Not imported because the
 * package does not export it; the frozen URI below is the standing proof that
 * this value still agrees with the encoder.
 */
const DEMO_KEY_MATERIAL_LENGTH = 32;

/**
 * A label widened to key-material length with trailing zero bytes.
 *
 * X25519 clamps its scalar before use, so a mostly-ASCII secret is a perfectly
 * valid secret key, and the resulting bytes read as their own label in a hex
 * dump. Deliberately not a hash: `hashBlake2s` is not re-exported from the
 * package root, and reaching around it into `@noble/hashes` would add an
 * undeclared direct dependency for no benefit that matters here (see the
 * not-a-secret note above).
 */
function demoLabelBytes(label: string): Uint8Array {
  const bytes = new Uint8Array(DEMO_KEY_MATERIAL_LENGTH);
  bytes.set(new TextEncoder().encode(label).slice(0, DEMO_KEY_MATERIAL_LENGTH));
  return bytes;
}

const demoDesktopSecretKey = demoLabelBytes('kangentic-demo-desktop-static-v1');

/** The in-process demo desktop's static keypair, standing in for a real desktop's. */
export const DEMO_DESKTOP_STATIC: X25519KeyPair = {
  secretKey: demoDesktopSecretKey,
  publicKey: x25519PublicKeyFrom(demoDesktopSecretKey),
};

/** The IKpsk0 pre-shared key for the demo ceremony. A real ceremony's equivalent is single-use and random. */
export const DEMO_PAIRING_TOKEN = demoLabelBytes('kangentic-demo-pairing-token-v1');

/**
 * Shown on the Devices screen as the paired desktop's relay, so it has to read
 * like a real address rather than announce itself as a fixture.
 *
 * It is never dialed: `connectionManager` diverges to the in-process peer
 * before any transport is built, keyed on the desktop static key rather than on
 * this string. It is also chosen to fail closed if a future bug ever did let it
 * through, since no relay is served at this host.
 */
export const DEMO_RELAY_ADDRESS = 'wss://demo.kangentic.com';

/**
 * The payload the demo ceremony actually runs on, built at call time so its
 * prologue-binding `protocolVersion` is always this build's own. The responder
 * is handed the same value, so the two prologues agree by construction and a
 * PROTOCOL_VERSION bump can never desync them.
 */
export function demoPairingPayload(): PairingQrPayload {
  return {
    desktopStaticPublicKey: DEMO_DESKTOP_STATIC.publicKey,
    pairingToken: DEMO_PAIRING_TOKEN,
    relayAddress: DEMO_RELAY_ADDRESS,
    // Never read: the demo is recognised by exact string match, never decoded
    // and never validated. Far-future so that a human who does decode the blob
    // out of curiosity is not misled into thinking it lapsed.
    expiresAt: '2099-12-31T23:59:59.000Z',
    protocolVersion: PROTOCOL_VERSION,
  };
}

/**
 * What the reviewer's QR image encodes: a genuine, correctly encoded pairing
 * URI, so the QR is indistinguishable in shape from a real one.
 *
 * FROZEN ON PURPOSE, and generated by `scripts/buildDemoPairingQr.mjs` rather
 * than computed here. Computing it would fold in the running build's
 * PROTOCOL_VERSION, so the next protocol bump would silently change the string
 * the app recognises while the QR already in Apple's hands still encoded the
 * old one, and the demo would die in review with nothing in the repo having
 * visibly changed. `tests/unit/demoPairing.test.ts` pins that this literal
 * still decodes to the key and token above, which is the drift alarm.
 */
export const DEMO_PAIRING_URI =
  'kangentic-pair://AV8Q-g1l9_V52GB2YbeuPqypWT0govfktLjbLIUAQRswa2FuZ2VudGljLWRlbW8tcGFpcmluZy10b2tlbi12MQAAAAAYd3NzOi8vZGVtby5rYW5nZW50aWMuY29tAAAAGDIwOTktMTItMzFUMjM6NTk6NTkuMDAwWgAAAAEz';

/**
 * The typeable alternative, for a reviewer whose camera will not cooperate.
 *
 * Deliberately URI-shaped rather than a bare word: the paste field is
 * placeholdered `kangentic-pair://...`, and a code that matches the format the
 * field advertises reads as a pairing link rather than as a backdoor. It is
 * also the string the deep link uses, so there is one thing to document.
 */
export const DEMO_PAIRING_SHORTCUT = 'kangentic-pair://demo';

/**
 * The shortest form, and the one the App Review notes actually ask for.
 *
 * The field's placeholder advertises `kangentic-pair://...`, but that is a hint
 * for the normal case, not a required format - and making a reviewer type a
 * scheme prefix to reach a demo is friction for no benefit. A bare word cannot
 * collide with a real code: every real pairing URI begins with
 * `kangentic-pair://`, so nothing that is a valid pairing link is also this.
 */
export const DEMO_PAIRING_WORD = 'demo';

/**
 * The query parameter `app/+native-intent.ts` sets on `/pair` to say "a demo
 * deep link brought us here, start the ceremony".
 *
 * A parameter rather than a direct call because `redirectSystemPath` can only
 * return a path; it has no way to reach into the app. Routing the intent
 * through the pairing screen also means the deep link takes exactly the same
 * code path as the camera and the paste field, rather than a fourth one of its
 * own that could drift.
 */
export const DEMO_DEEP_LINK_PARAM = 'demo';

/**
 * Whether a scanned or typed string is the demo code.
 *
 * MUST be consulted BEFORE `validateScannedQr`, and a match must never fall
 * through into it. Two reasons, and the second is the load-bearing one:
 *
 * 1. `DEMO_PAIRING_SHORTCUT` is not a decodable payload at all, so validation
 *    would reject it as malformed.
 * 2. `DEMO_PAIRING_URI` *would* decode, and would then be checked against the
 *    running build's PROTOCOL_VERSION. The literal is frozen, so the first
 *    protocol bump would start rejecting the very QR already sitting in App
 *    Review's hands, as `version-incompatible`, with nothing in this repository
 *    having changed. Exact string matching is what makes the demo permanent.
 *
 * Comparison is exact after trimming. The two typed forms accept any case,
 * because that is what a human enters; the encoded URI does not, because
 * base64url is case-significant and a case-folded match there would be a bug
 * pretending to be leniency.
 */
export function isDemoPairingCode(input: string): boolean {
  const trimmed = input.trim();
  if (trimmed === DEMO_PAIRING_URI) return true;
  const lowered = trimmed.toLowerCase();
  return lowered === DEMO_PAIRING_SHORTCUT || lowered === DEMO_PAIRING_WORD;
}

/**
 * Whether a persisted trust anchor is the demo one.
 *
 * THE SOLE DISCRIMINATOR between a demo pairing and a real one, everywhere
 * downstream. Keyed on the desktop static public key rather than on
 * `relayAddress` so that no real desktop can collide with it however its relay
 * is addressed, and so that a self-hosted relay that happened to share the demo
 * hostname could not tip a real pairing into fixture mode.
 *
 * Not constant-time, deliberately: both sides are non-secret, one of them is a
 * compile-time constant in a public repository, and there is no oracle to
 * protect. `constantTimeEqual` is also not re-exported from the package root.
 */
export function isDemoAnchor(anchor: Pick<TrustAnchor, 'desktopStaticPublicKey'>): boolean {
  const expected = DEMO_DESKTOP_STATIC.publicKey;
  const actual = anchor.desktopStaticPublicKey;
  if (actual.length !== expected.length) return false;
  for (let index = 0; index < expected.length; index += 1) {
    if (actual[index] !== expected[index]) return false;
  }
  return true;
}
